# Generated by Django 6.0.3 on 2026-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('stretch', 'Stretch'), ('sport', 'Sport')], default='strength', max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=60)),
                ('instructions', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('muscle_groups', models.ManyToManyField(blank=True, related_name='exercises', to='main_app.musclegroup')),
            ],
        ),
    ]
