# Generated by Django 6.0.3 on 2026-03-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_workout_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('start_dt', models.DateTimeField()),
                ('interval', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workoutplan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workouttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('plan', 'template', 'order')},
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='plans', through='main_app.WorkoutTemplatePlan', to='main_app.workouttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutplan',
            unique_together={('user', 'title')},
        ),
    ]
