# Generated by Django 6.0.3 on 2026-03-05 16:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_workoutplan_workouttemplateplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='main_app.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttemplateplan',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_dt',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 5, 16, 51, 53, 816677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
