# Generated by Django 6.0.3 on 2026-03-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_workout_plan_workoutplan_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
