# Generated by Django 6.0.3 on 2026-03-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_workouttemplate_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttemplateitem',
            old_name='distance_meters',
            new_name='distance',
        ),
        migrations.AddField(
            model_name='workouttemplateitem',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('km', 'km'), ('mi', 'mi')], max_length=5, null=True),
        ),
    ]
