# Generated by Django 6.0.3 on 2026-03-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_distance_meters_workouttemplateitem_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutitem',
            old_name='distance_meters',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='workoutitem',
            old_name='duration_seconds',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='workouttemplate',
            old_name='duration_minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='workouttemplateitem',
            old_name='duration_seconds',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='workoutitem',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('km', 'km'), ('mi', 'mi')], max_length=5, null=True),
        ),
    ]
