# Generated by Django 6.0.3 on 2026-03-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_distance_meters_workoutitem_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='cycles',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
