# Generated by Django 6.0.3 on 2026-03-09 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profile_weightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplateplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='main_app.workoutplan'),
        ),
        migrations.AlterField(
            model_name='workouttemplateplan',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='main_app.workouttemplate'),
        ),
    ]
